# Generated by Django 2.0.13 on 2019-03-29 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseClientRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('modifiedOn', models.DateTimeField(auto_now=True)),
                ('active', models.IntegerField(choices=[(0, 'InActive'), (2, 'Active')], default=2)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.Client')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.Expense')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
